### ISSUE TITLE
How to modify the db.gz file?

### ISSUE THREAD

**Issue by reillychase** [zhangyoufu/unifi-backup-decrypt#2]
I am trying to modify the database, but I can't restore it. I've tried the following:

mongorestore db.gz
Failed: file db_stat.gz does not have .bson extension

mongorestore --gzip db.gz
Failed: file db_stat.gz does not have .bson extension

mongorestore --gzip --archive=db.gz
Failed: stream or file does not appear to be a mongodump archive

**Comment by zhangyoufu** [comment]
I was wrong. The db.gz is not exported by `mongodump`.

You can view the content by `gunzip -c db.gz | bsondump`.

**Comment by reillychase** [comment]
Thanks! Sorry to reopen this issue, but I am trying to dump the database into readable format (gunzip -c db.gz | bsondump helped), modify it, then put it back together to ready it for restore.

I haven't figured out how to take the bsondump and "undump" it.

I was not able to find contact information to work with you on this, but if anyone wants to work together, feel free to DM me here

**Comment by reillychase** [comment]
Still can't figure it out
