### ISSUE TITLE
Deriving the key and IV

### ISSUE THREAD

**Issue by mdvthu** [zhangyoufu/unifi-backup-decrypt#5]
Any chance of putting some background info in the README?

These are magic numbers to me. It would be good to see how to recreate

**Comment by zhangyoufu** [comment]
You can find related logic in `ace.jar` with something like [JD-GUI](https://java-decompiler.github.io/) or [Bytecode Viewer](https://github.com/Konloch/bytecode-viewer). It is obfuscated but not hard to find. I won't add detail in README, but any contribution is welcomed.
